---
ignore:
  - vulnerability: GHSA-9493-h29p-rfm2
    package:
      name: github.com/opencontainers/runc
      version: v1.2.5
  - vulnerability: GHSA-cgrx-mc8f-2prm
    package:
      name: github.com/opencontainers/runc
      version: v1.2.5
  - vulnerability: GHSA-qw9x-cqr3-wc7r
    package:
      name: github.com/opencontainers/runc
      version: v1.2.5
  - vulnerability: CVE-2025-61723
    package:
      name: stdlib
      version: go1.23.7
  - vulnerability: CVE-2025-61725
    package:
      name: stdlib
      version: go1.23.7
  - vulnerability: CVE-2025-47907
    package:
      name: stdlib
      version: go1.23.7
  - vulnerability: CVE-2025-58187
    package:
      name: stdlib
      version: go1.23.7
  - vulnerability: CVE-2025-58188
    package:
      name: stdlib
      version: go1.23.7
  - vulnerability: CVE-2025-4674
    package:
      name: stdlib
      version: go1.23.7
  - vulnerability: CVE-2025-22871
    package:
      name: stdlib
      version: go1.23.7
