---
version: 3

vars:
  REMOTE_URL: https://raw.githubusercontent.com
  REMOTE_URL_REF: v0.13.0
  REMOTE_URL_REPO: schubergphilis/mcvs-golang-action

includes:
  remote:
    taskfile: >-
      {{.REMOTE_URL}}/{{.REMOTE_URL_REPO}}/{{.REMOTE_URL_REF}}/Taskfile.yml
    vars:
      GCI_SECTIONS: >-
        -s standard
        -s default
        -s "Prefix(schubergphilis/mcvs-integrationtest-services)"
