---
name: docker-mcvs-registry
"on":
  push:
    tags:
      - "*"
    paths:
      - "registry/**"
  pull_request:
    paths:
      - "registry/**"
permissions:
  contents: read
  packages: write
env:
  BUILD_IMAGE_NAME: mcvs-registry
  DOCKERFILE_CONTEXT: ./registry
  IMAGE_MANIFEST_LIST: nginx/nginx:1.27.0-alpine
  IMAGE_MANIFEST_SINGLE: nginx/nginx:1.27.0-alpine-slim-amd64
  REGCTL_VERSION: v0.8.0
  REGISTRY_LOCAL: localhost:5000
  REGISTRY_REMOTE: public.ecr.aws
  REGISTRY_VERSION: 3.0.0-rc.2
jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build-args:
          - mcvs-registry
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install regctl
        uses: regclient/actions/regctl-installer@main
        with:
          release: ${{ env.REGCTL_VERSION }}
      - name: Create registry backup directory
        run: mkdir -p ${{ env.DOCKERFILE_CONTEXT }}/backup-registry
      - name: Pull images data and prepare context directory
        shell: bash
        run: |
          #!/bin/bash

          # run local registry
          docker run -d \
            -p 5000:5000 \
            --name mcvs-registry-tmp \
            registry:${{ env.REGISTRY_VERSION }}

          # disable tls for local tmp registry
          regctl registry set --tls disabled ${{ env.REGISTRY_LOCAL }}

          # import image with manifest list
          regctl \
            image \
            copy --digest-tags \
            ${{ env.REGISTRY_REMOTE }}/${{ env.IMAGE_MANIFEST_LIST }} \
            ${{ env.REGISTRY_LOCAL }}/${{ env.IMAGE_MANIFEST_LIST }}

          # import image with single manifest
          regctl \
            image \
            copy --digest-tags \
            ${{ env.REGISTRY_REMOTE }}/${{ env.IMAGE_MANIFEST_SINGLE }} \
            ${{ env.REGISTRY_LOCAL }}/${{ env.IMAGE_MANIFEST_SINGLE }}

          # export images files to backup directory
          docker \
            cp \
            mcvs-registry-tmp:/var/lib/registry \
            ${{ env.DOCKERFILE_CONTEXT }}/backup-registry

          # clean up the registry container
          docker rm -f mcvs-registry-tmp

      - uses: schubergphilis/mcvs-docker-action@v0.6.1
        with:
          build-args: ${{ matrix.build-args }}
          context: ${{ env.DOCKERFILE_CONTEXT }}
          dockle-accept-key: "curl,HOME,libcrypto3,libssl3,PATH"
          images: ghcr.io/${{ github.repository }}/${{ matrix.build-args }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get new registry catalog
        if: ${{ github.event_name == 'pull_request' }}
        shell: bash
        run: |
          #!/bin/bash
          docker images

          docker run -d \
            -p 5005:5000 \
            --name mcvs-registry \
            ghcr.io/${{ github.repository }}/${{ env.BUILD_IMAGE_NAME }}:pr-${{ github.event.number }}

          curl --silent http://localhost:5005/v2/_catalog

          docker rm --force mcvs-registry
